server {
    listen 80;

    location /api/ {
        # API
        proxy_pass http://spring-boot-api:8082/;
    }

    location / {
        # UI
        proxy_pass http://nginx-html-server:8081/;
    }
}
