name: Docker CI

on:
    push:
        branches:
            - "main"

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: DockerHub login
              run: |
                  echo ${{secrets.DOCKERHUB_TOKEN}} | docker login
                  -u ${{secrets.DOCKERHUB_USERNAME}}
                  --password-stdin

            - name: Build Docker image (linux/x86_64)
              run: |
                  docker buildx build
                  -t ${{secrets.DOCKERHUB_USERNAME}}/feni-aws:latest
                  --platform linux/x86_64

            - name: Push Docker image
              run: docker push ${{secrets.DOCKERHUB_USERNAME}}/feni-aws:latest
